### ISSUE TITLE
Required plugin/rust verison for solana 1.18.14

### ISSUE THREAD

**Issue by jay-ginco** [metaplex-foundation/digital-asset-validator-plugin#73]
Hi, we are running solana validator node (devnet and mainnet) with 1.18.14 verison, and want to corporate this plugin with the same, kindly mentioned whats the recommended rust version to use to build latest code of plugin. 

I have tried executing docker/build.sh file with rust 1.75-bullseye and 1.73-bullseye version, and while using the plugin.so artifact with validator node, it gives error like:
` solana_geyser_plugin_manager::geyser_plugin_service] Starting GeyserPluginService from config files: ["/var/solana/config/geyser-plugin.json"]
memory allocation of 140720342429841 bytes failed`

Please suggest.

**Comment by danenbm** [comment]
Release tag with Solana 1.18.11:
https://github.com/metaplex-foundation/digital-asset-validator-plugin/releases/tag/v1.9.0

Docker image for release 1.9.0 with Rust 1.75.0 and Solana 1.18.11:
https://github.com/metaplex-foundation/digital-asset-validator-plugin/pkgs/container/plerkle-test-validator/255585605?tag=v1.9.0-1.75.0-v1.18.11

Relevant crates releases:
https://crates.io/crates/plerkle_serialization
https://crates.io/crates/plerkle_messenger

These should work for your 1.18 build!!! Please re-open this issue if it doesn't work for you!
